### ISSUE TITLE
hidden message fixer 

### ISSUE THREAD

**Issue by emnemdesign** [emnemdesign/hidden-message-fixer#1]
@thomasjbradley not sure how to attempt this exercise it has a parse token error

**Comment by thomasjbradley** [comment]
Sorry, can't help you much without giving you the answers. It should have a parse error, the purpose is to fix the errors until it's working properly.

**Comment by emnemdesign** [comment]
I figured it out but when I run it through Markbot it says "Uncaught Exception:
TypeError: Cannot read property 'match' of undefined
    at shouldIncludeError (/Applications/Markbot.app/Contents/Resources/app.asar/checks/css/validation.js:40:51)
    at /Applications/Markbot.app/Contents/Resources/app.asar/checks/css/validation.js:140:15
    at Array.forEach (native)
    at /Applications/Markbot.app/Contents/Resources/app.asar/checks/css/validation.js:134:20
    at Parser.<anonymous> (/Applications/Markbot.app/Contents/Resources/app.asar/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (/Applications/Markbot.app/Contents/Resources/app.asar/node_modules/xml2js/lib/xml2js.js:445:26)
    at emit (/Applications/Markbot.app/Contents/Resources/app.asar/node_modules/sax/lib/sax.js:639:35)
    at emitNode (/Applications/Markbot.app/Contents/Resources/app.asar/node_modules/sax/lib/sax.js:644:5)"

**Comment by thomasjbradley** [comment]
Have you committed and synced your code recently, so I can look at it?

**Comment by emnemdesign** [comment]
i just did

**Comment by thomasjbradley** [comment]
Have you recently tried it in Markbot? I'm not seeing any problems.
